quarkus.application.name=course-service
quarkus.http.port=8083

# SmallRye GraphQL & Apollo Federation
quarkus.smallrye-graphql.federation.enabled=true
quarkus.smallrye-graphql.federation.batch-resolving-enabled=true
quarkus.smallrye-graphql.ui.enable=true
quarkus.smallrye-graphql.root-path=/graphql
quarkus.smallrye-graphql.schema-include-directives=true

# Logging
quarkus.log.level=INFO
quarkus.log.category."com.school".level=DEBUG

# OpenTelemetry Distributed Tracing
quarkus.otel.enabled=true
quarkus.otel.service.name=course-service
quarkus.otel.exporter.otlp.endpoint=http://localhost:4317
%test.quarkus.otel.enabled=false

